#server setting
server:
  port: 8080

# profile 설정
# application-{spring:profiles:active}.yml 설정파일에 레벨별로 환경변수 설정
# 개발 레벨(local, dev, stage, live, qc 등)
---
spring:
  application:
    name: "mokkozi"
  profiles:
    active:
#      - local
#    group:
#      local:
#        - site-local
#        - db-local
#      dev:
#        - site-dev
#        - db-dev

    include:
      - db
#      - site
      # - my-service
#---
#spring:
#  profiles:
#    active: dev
#---
#spring:
#  profiles:
#    active: prd